### PR TITLE
Make app creating factory async

### LINKED ISSUE #10: Demonstrate gunicorn usage
Would be nice to have an ability to run the demo under gunicorn.
Need a gunicorn entrypoint file.
See https://stackoverflow.com/questions/47266296/running-aiohttp-server-using-gunicorn

### PR DESCRIPTION
**Pull request by gyermolenko**
To be able to run application with gunicorn I made the application creating factory async (fix #10).
Unfortunately I got `unrecognized arguments` error from 
```
gunicorn aiohttpdemo_polls.main:init_app --bind localhost:8080 --worker-class aiohttp.GunicornWebWorker
```
so I've also substituted `parse_args` with `parse_known_args` as a workaround:

```
# ignore unknown options
options, unknown = ap.parse_known_args(argv)
```

Please review `get_config` function usages and parts of logic related to usage of `argv` and `get_config(['-c', USER_CONFIG_PATH.as_posix()])`. It looks ugly but I can't find a better way (if we still want command line args).

### CODE REVIEW

**Comment by farhanmannan** [comment]
As soon as the tests pass let's merge this!

**Comment by jettify** [comment]
what about other demos? any plan to make factories there?

**Comment by webknjaz** [comment]
It seems to me that you re-implement what's available in https://pypi.org/project/aio_manager/, is it your intention to avoid external dependencies?

**Comment by gyermolenko** [comment]
@webknjaz 
I don't avoid external dependencies. `aio_manager` looks like an overkill, but `aio_yamlconfig` can probably fit. Although I was thinking about `yamllint`. Need some opinions from others.

We have at least 3 kinds of app start: 
1. python main.py
2. tests
3. gunicorn

So if we want flexible app configuration - what are best practices here? 
Current implementation is to pass `-c ./path/to/config_file.xxx` from command line for start option 1... and  2 workarounds (for start options 2 and 3).

**Comment by gyermolenko** [comment]
@jettify 
> what about other demos? any plan to make factories there?

I can do that, sure. Do we want other similarities between different demos?

**Comment by webknjaz** [comment]
I'd say priority for config lookup should follow unix-way:
1. passed as CLI arg (`-c, --config`)

    1.1. (maybe) `$PWD/config/app_config_name.yaml`

2. ` ~/.app_config_name.yaml`

3. `/etc/app_config_name.yaml`

**Comment by jettify** [comment]
@gyermolenko not sure but essential parts should be the same I think like factories, new APIs

**Comment by jettify** [comment]
@webknjaz would you like submit PR with your suggestion?

**Comment by webknjaz** [comment]
@jettify i'll do if i have time

**Pull request merged**
