### PR TITLE
WIP: Describe db tables in declarative style

### PR DESCRIPTION
**Pull request by gyermolenko**
Rather a question than PR:
what do you think of declarative style for tables?

Pros:
- it is cleaner
- flask apps use this style quite often, probably because of `flask-sqlalchemy` extension examples

Cons:
- user can't use session.query(TableName) with `aiopg`
- I was able to do selects, but failed in voting with some choice in the app. 
This type of query didn't work unfortunately:
`stmt = Choice.__table__.update().where(User.id == 1).values(choice_text='xxxxx')`

### CODE REVIEW

**Comment by asvetlov** [comment]
I don't think we need this form.
Declared classes are unusable :(

**Comment by gyermolenko** [comment]
@asvetlov thanks for reply.
Django world is spinning around this type of declaration, just sayin ))

You mean unusable in asyncio world or in general? Or you just don't like it?

**Comment by asvetlov** [comment]
Please let me elaborate.

Let's consider 
```
class Question(Base):
    __tablename__ = 'question'

    id = Column(Integer, primary_key=True)
    question_text = Column(String(200), nullable=False)
    pub_date = Column(Date, nullable=False)
```

`declarativ_base` approach is preferred form for SQLAlchemy (while I still remember the times when this way wasn't exist).

But for SQLAlchemy it makes sense: People can do many thing with `Question` object.
But for `aiopg.sa` the only available thing is `Question.__table__`, that's it.
That's why I call the `Question` class *unusable* -- just a table declaration is enough.

Django and SQLAlchemy ORM is another story -- but `aiopg.sa` don't support it unfortunately.

**Comment by webknjaz** [comment]
I personally prefer declarative way of keeping table in code (aka classes) and then create aliases for async code if needed.

This looks cleaner and [readability counts](https://www.python.org/dev/peps/pep-0020/):
```python
class SomeEntity(Base):
    ...

SomeEntityTbl = SomeEntity.__table__
```

Thus even though I cannot use the classes for queries I write my models like this.

// just wanted to add my 2 cents here

**Pull request closed without merging**
