### PR TITLE
capture error log when use error_middleware

### PR DESCRIPTION
**Pull request by xiaohuanshu**

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
Good idea, thanks.

Unfortunately, I can't merge anything until the CI has been updated. Someone will need to migrate the setup from Travis to Github's CI.

**Comment by Dreamsorcerer** [comment]
Please merge master. Then the tests will complete.

**Comment by xiaohuanshu** [comment]
> Please merge master. Then the tests will complete.

Shoud i resubmit it?

**Comment by Dreamsorcerer** [comment]
Either resubmit, or merge master into this branch. Thanks.

**Pull request merged**
