### PR TITLE
Update test_integration.py

### PR DESCRIPTION
**Pull request by art2limit**
## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by art2limit** [comment]
Похоже у меня нет прав пушить сюда даже, в пулл реквест по этому оставлю ответ по заданию тут 

``"""Require running database server"""

from aiohttpdemo_polls.db import choice


async def test_index(cli, tables_and_data):
    response = await cli.get('/')
    assert response.status == 200
    # TODO: resolve question with html code "&#39;" instead of apostrophe in
    # assert 'What\'s new?' in await response.text()
    assert 'Main' in await response.text()


async def test_results(cli, tables_and_data):
    response = await cli.get('/poll/1/results')
    assert response.status == 200
    assert 'Just hacking again' in await response.text()


async def test_vote(cli, tables_and_data):

    question_id = 1
    choice_text = 'Not much'

    async with cli.server.app['db'].acquire() as conn:
        res = await conn.execute(
            choice.select(
            ).where(choice.c.question_id == question_id)
             .where(choice.c.choice_text == choice_text)
        )
        not_much_choice = await res.first()
        not_much_choice_id = not_much_choice.id
        votes_before = not_much_choice.votes

        response = await cli.post(
            f'/poll/{question_id}/vote',
            data={'choice': not_much_choice_id}
        )
        assert response.status == 200

        res = await conn.execute(
            choice.select(
            ).where(choice.c.question_id == question_id)
             .where(choice.c.choice_text == choice_text)
        )
        not_much_choice = await res.first()
        votes_after = not_much_choice.votes

        assert votes_after == votes_before + 1
``

**Comment by Arfey** [comment]
what?

**Comment by gyermolenko** [comment]
@art2limit 
> Похоже у меня нет прав пушить сюда даже, в пулл реквест по этому оставлю ответ по заданию тут

`master` is protected branch. What you want to do is 
- create fork
- make a branch with a fix
- create PR agains master of source repo

At what point do you have troubles? Is this yours or @Lex0ne `s?

**Comment by art2limit** [comment]
Yep, sorry, it's for https://github.com/Lex0ne/aiohttp-demos/pulls and i miss with projects

**Pull request closed without merging**
